 version: 2
 jobs:
   deploy:
     machine:
       enabled: true
     steps:
       - run: |
             if [ "$SSH_HOST" = "1.2.3.4" ]; then
                 echo hello
             fi
 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy
#           filters:
#             branches:
#               only: branch_test # only deploy on the main branch11
